export type UPDATE_GREETING = "UPDATE_GREETING";
export type INCREMENT = "INCREMENT";
export type UPDATE_TOKEN = "UPDATE_TOKEN";
export type UPDATE_LOCAL_STORAGE = "UPDATE_LOCAL_STORAGE";
export type UPDATE_GISTS = "UPDATE_GISTS";
export type DELETE_GIST = "DELETE_GIST";
export type EDIT_GIST = "EDIT_GIST";
export type EDIT_FILE = "EDIT_FILE";
export type CREATE_GIST = "CREATE_GIST";
export type GET_FILES = "GET_FILES";
export type DELETE_FILE = "DELETE_FILE";
export type UPDATE_IS_AUTHENTICATED = "UPDATE_IS_AUTHENTICATED";
export type UPDATE_SELECTED_GIST = "UPDATE_SELECTED_GIST";

export type UPDATE_IS_LOADING = "UPDATE_IS_LOADING";

export const UPDATE_GREETING: UPDATE_GREETING = "UPDATE_GREETING";
export const INCREMENT: INCREMENT = "INCREMENT";
export const UPDATE_TOKEN: UPDATE_TOKEN = "UPDATE_TOKEN";
export const UPDATE_LOCAL_STORAGE: UPDATE_LOCAL_STORAGE =
  "UPDATE_LOCAL_STORAGE";
export const DELETE_GIST: DELETE_GIST = "DELETE_GIST";
export const EDIT_GIST: EDIT_GIST = "EDIT_GIST";
export const EDIT_FILE: EDIT_FILE = "EDIT_FILE";
export const UPDATE_GISTS: UPDATE_GISTS = "UPDATE_GISTS";
export const CREATE_GIST: CREATE_GIST = "CREATE_GIST";
export const GET_FILES: GET_FILES = "GET_FILES";
export const DELETE_FILE: DELETE_FILE = "DELETE_FILE";
export const UPDATE_IS_AUTHENTICATED: UPDATE_IS_AUTHENTICATED =
  "UPDATE_IS_AUTHENTICATED";
export const UPDATE_IS_LOADING: UPDATE_IS_LOADING = "UPDATE_IS_LOADING";

export const UPDATE_SELECTED_GIST: UPDATE_SELECTED_GIST =
  "UPDATE_SELECTED_GIST";
